coverage:
  precision: 2
  round: nearest
  range: "50...90"
  ignore:
    - "witlab/models/**/timeIntegration.py"
    - "witlab/utils/devutils.py"
    - "witlab/utils/atlases.py"
    - "witlab/models/multimodel/builder/aln.py"
  status:
    project:
      default:
        enabled: yes
        target: auto
        threshold: 5%
    patch: off
