site_name: witlab
repo_name: 'WitLaboratory/witlab'
repo_url: https://github.com/WitLaboratory/witlab

theme:
  name: "material"

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/WitLaboratory
      name: witlab on Twitter

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: sphinx
  - mknotebooks:
      binder: true
      binder_service_name: "gh"
      binder_branch: "master"
  - include-markdown

markdown_extensions:
  - codehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences

extra_javascript:
  - js/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
google_analytics:
  - UA-189722517-1
  - auto
